### ISSUE TITLE
Allowing options for the terminal

### ISSUE THREAD

**Issue by dariuskramer** [ahendriksen/ob-tmux#7]
Hi

Can you add the possibility to pass options to the terminal spawn by ob-tmux?

Example: I use i3wm and I can put a terminal in the scratchpad which will act as a dropdown terminal. If I can set an option for the ob-tmux terminal, like window title, I can make a window rule in i3wm where this terminal will be put in the scratchpad automatically.

Thank you for your work btw :)

**Comment by ahendriksen** [comment]
Hi, 

Thanks for the kind words. I believe what you are asking is already possible. Have you tried editing the default terminal?

Like this:
```
(setq org-babel-default-header-args:tmux
  '((:results . "silent")		;
    (:session . "default")	; The default tmux session to send code to
    (:socket  . nil)              ; The default tmux socket to communicate with
    ;; You can use "xterm" and "gnome-terminal".
    ;; On mac, you can use "iterm" as well.
    (:terminal . "xterm -T scratchpad"))) ;; <---------------------------
```

**Comment by ahendriksen** [comment]
My bad, this actually breaks xterm. 

See: https://github.com/ahendriksen/ob-tmux/blob/73bed0ebad27f0ad57ea67582494543eb2fab73d/ob-tmux.el#L190

Perhaps this line should test if the terminal contains xterm instead of testing for equality. Furthermore, the ob-tmux should perhaps not supply the window title?

 If you get this to work, could you possibly send a pull request?

**Comment by dariuskramer** [comment]
I made a pull request, #8, that fixes the issue. I'm not an experienced Elisp programer so any feedback or criticism are welcome :)

**Comment by ahendriksen** [comment]
Thanks. Your PR has been merged!
